FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/
COPY packages/shared/package*.json ./packages/shared/
RUN npm install
COPY . .
RUN npx prisma generate --schema=apps/api/prisma/schema.prisma
EXPOSE 3000
CMD ["npm", "run", "dev"]
